listing = [0, 1, 2, 3]
listing = str(listing[0:4])
file = open("intlisting.txt", "w")
for i in listing:
    file.write(i)
file.close()
file = open("intlisting.txt", "r")
content = file.readlines()
file.close()
print (content)
file = open("intlisting.txt", "a")
for i in listing:
    file.write(str(i) + "\n")
file.close()
file = open("intlisting.txt", "r")
file.seek(0)
content = file.read()
print (content)
file = open("intlisting.txt", "r+")
file.write("r+ allows us to read and write")
content = file.readlines()
file.close()
print(content)
file = open ("intlisting.txt", "w+")
file.write("w+ This allows us to write and read, this will overtype on the file  ")
content = file.readlines()
file.close()
print(content)
file = open("intlisting.txt", "a")
file.write("a allows us to append the file, adding on to the end of it  ")
file.close()
print(content)
file = open("intlisting.txt", "a+")
file.write("the a+ allows us to append and read the file.  ")
content = file.readlines()
file.close()
print(content
      )
